f=open("E:\\python programing practice\\lab-10\\1ST.txt","r")
f1=open("E:\\python programing practice\\lab-10\\2ND.txt","w")
data=f.read()
data=data.replace(" a ","_____")
data=data.replace(" an ","_____")
data=data.replace(" the ","_____")
data=data.replace(" A ","_____")
data=data.replace(" AN ","_____")
data=data.replace(" THE ","_____")
f1.write(data)
f.close()
f1.close()
